### ISSUE TITLE
ImportError: cannot import name 'QuantStub' from 'torch.ao.quantization'

### ISSUE THREAD

**Issue by houruiyan** [snap-stanford/SATURN#3]
Hello,  when I run saturn, I meet this problem. 

```
Traceback (most recent call last):
  File "/data/users/houruiyan/software/saturn/train-saturn.py", line 36, in <module>
    from pretrain_utils import *
  File "/data/users/houruiyan/software/saturn/pretrain_utils.py", line 9, in <module>
    from utils.transformations import *
  File "/data/users/houruiyan/software/saturn/utils/transformations.py", line 4, in <module>
    import torchvision.datasets as datasets
  File "/home/houruiyan/.conda/envs/run_saturn/lib/python3.7/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "/home/houruiyan/.conda/envs/run_saturn/lib/python3.7/site-packages/torchvision/models/__init__.py", line 17, in <module>
    from . import detection, optical_flow, quantization, segmentation, video
  File "/home/houruiyan/.conda/envs/run_saturn/lib/python3.7/site-packages/torchvision/models/quantization/__init__.py", line 3, in <module>
    from .mobilenet import *
  File "/home/houruiyan/.conda/envs/run_saturn/lib/python3.7/site-packages/torchvision/models/quantization/mobilenet.py", line 1, in <module>
    from .mobilenetv2 import *  # noqa: F401, F403
  File "/home/houruiyan/.conda/envs/run_saturn/lib/python3.7/site-packages/torchvision/models/quantization/mobilenetv2.py", line 5, in <module>
    from torch.ao.quantization import DeQuantStub, QuantStub
ImportError: cannot import name 'QuantStub' from 'torch.ao.quantization' 
```

my code is like this

#!/bin/bash

```
python /data/users/houruiyan/software/saturn/train-saturn.py \
--in_data /data/users/houruiyan/run_saturn/path_matrix.csv \
--in_label_col=cell_type --ref_label_col=cell_type \
--num_macrogenes=2000     --hv_genes=8000 \
--centroids_init_path=/data/users/houruiyan/run_saturn//four_centroids.pkl \
--score_adata --ct_map_path=/data/users/houruiyan/run_saturn/cellType_info.csv \
--work_dir=. \
--device_num=7
```

Could you help me? Thank you!

**Comment by Yanay1** [comment]
Sorry for the incompleteness of the requirements file, I'll work on fixing that.

The torch versions SATURN was developed with are as follows:

```
torch                       1.12.1+cu113

torch-cluster               1.6.0

torch-geometric             2.1.0.post1

torch-scatter               2.0.9

torch-sparse                0.6.15

torch-spline-conv           1.2.1

torchaudio                  0.12.1+cu113

torchmetrics                0.9.3

torchvision                 0.13.1+cu113

```

So installing those using https://pytorch.org/get-started/locally/ should help, although there might be more requirements missing (all can be installed using pip).

**Comment by houruiyan** [comment]
Thank you very much for your quick reply! That solved. Thanks!
