### ISSUE TITLE
RuntimeError: stack expects a non-empty TensorList

### ISSUE THREAD

**Issue by zhuojiuqingyun** [snap-stanford/SATURN#78]
Dear authors,
Thank you very much for making this great tool.
I got the following error while training SATURN.
`!python3 ../../train-saturn.py --in_data=data/xenia_hydra_stylpis_run.csv --in_label_col=cell_type --ref_label_col=cell_type --num_macrogenes=2000   --hv_genes=8000  --centroids_init_path=saturn_results/fz_centroids.pkl --work_dir=.  --device_num=0`
```
Global seed set to 0
Using Device 0
Set seed to 0
Traceback (most recent call last):
  File "/home/users/Ruijie/tools/SATURN/Vignettes/bleach/../../train-saturn.py", line 1064, in <module>
    trainer(args)
  File "/home/users/Ruijie/tools/SATURN/Vignettes/bleach/../../train-saturn.py", line 506, in trainer
    adata, species_gene_embeddings = load_gene_embeddings_adata(
  File "/home/users/Ruijie/tools/SATURN/data/gene_embeddings.py", line 114, in load_gene_embeddings_adata
    species_to_gene_embeddings = {
  File "/home/users/Ruijie/tools/SATURN/data/gene_embeddings.py", line 115, in <dictcomp>
    species_name: torch.stack([
RuntimeError: stack expects a non-empty TensorList
```
And this is my code for csv as input
```
df = pd.DataFrame(columns=["path", "species", "embedding_path"])
df["species"] = ["xenia", "hydra","stylpis"]
df["path"] = ["data/bleach_data.h5ad", "data/Hydra_data.h5ad","data/Spis_adult_data.h5ad"]

##### CHANGE THESE PATHS #####
xenia_embedding_path = "/home/users/Ruijie/tools/SATURN/Vignettes/bleach/protein_embedding/xenia.proteins.gene_symbol_to_embedding_ESM2.pt"
hydra_embedding_path = "/home/users/Ruijie/tools/SATURN/Vignettes/bleach/protein_embedding/hydra_protein.gene_symbol_to_embedding_ESM2.pt"
stylpis_embedding_path = "/home/users/Ruijie/tools/SATURN/Vignettes/bleach/protein_embedding/Stylophora_pistillata_protein.gene_symbol_to_embedding_ESM2.pt"

##############################
df["embedding_path"] = [xenia_embedding_path, hydra_embedding_path,stylpis_embedding_path]
df.to_csv("data/xenia_hydra_stylpis_run.csv", index=False)
```
Could you give me some advices.

Yours sincerely.
Ruijie

**Comment by s-weissbach** [comment]
Hi, I face a similar problem. 
I did modify the protein_embeding file for human to have ENSEMBL IDs and match my h5ad file. Could that cause any downstream errors?
Otherwise, my code for creating the dataframe:
```python
df = pd.DataFrame(columns=["path", "species", "embedding_path"])
df["species"] = ["human", "mouse"]
df["path"] = [f"{os.getcwd()}/human_sample.h5ad", f"{os.getcwd()}/mouse_sample.h5ad"]

##### CHANGE THESE PATHS #####
human_embedding_path = f"{os.getcwd()}/resources/protein_embeddings_export/ESM2/mouse_embedding.torch"
mouse_embedding_path = f"{os.getcwd()}/resources/protein_embeddings_export/ESM2/human_embedding_ensembl.torch"
##############################
df["embedding_path"] = [human_embedding_path, mouse_embedding_path]
df.to_csv("saturn_run.csv", index=False)
``` 

I verified that all paths are correct.

**Comment by s-weissbach** [comment]
For me the problem occured, because I had ENSEMBL IDs in my h5ad file and genesymbol in the protein encoding. I just did update the protein encoding file to have ENSEMBL IDs using the gtf file and it worked afterwards.

**Comment by zhuojiuqingyun** [comment]
> For me the problem occured, because I had ENSEMBL IDs in my h5ad file and genesymbol in the protein encoding. I just did update the protein encoding file to have ENSEMBL IDs using the gtf file and it worked afterwards.

May I ask you for your h5ad strcuture? I wonder about the ENSEMBL IDs in your h5ad file, beacuse  I didn't use data from ENSEMBL. Is there a special obs column for ENSEMBL IDs that maches the protein embedding?

**Comment by s-weissbach** [comment]
@zhuojiuqingyun, I did check it within .var dataframe, where it is set as the index column. I did this like this:
``` python
# check for IDs
sample = sc.read("/path/to/file")
print(sample.var)
protein_encoding = torch.load("path/to/file")
print(protein_encoding.keys()[:10])
```
in case that they don't match I did quickly parse from the GTF file the two IDs. Note that I did remove the version, maybe that is different for you.
```python
# prepare a dict for genesymbol -> ensembl
gtf = pd.read_csv("/path/to/gencode.v47.annotation.gtf", sep="\t", comment="#")
symbol2ensembl = {}
for row in gtf.iloc[:,8]:
    tmp = {}
    for val in row.split(";"):
        if len(val.strip().split(" ")) == 1: continue
        key, value = val.strip().split(" ")
        key = key.strip()
        value = value.strip().replace('"', '')
        if key == "gene_id":
            # remove gene version to match h5ad file
            value = value.split(".")[0]
        tmp[key] = value
    symbol2ensembl[tmp['gene_name']] = tmp['gene_id']
```
and for modifiying the protein encoding
```python
ensembl_protein_embedding = {}
count = 0
for key, value in protein_encoding.items():
    if key in symbol2ensembl:
        ensembl_protein_embedding[symbol2ensembl[key]] = value
    else:
        print(key, end=", ")
        ensembl_protein_embedding[key] = value
        count += 1
print(f"\n Without ENSEMBL ID: {count}/{len(ensembl_protein_embedding)}")
torch.save(ensembl_protein_embedding,"/path/to/outfile.torch")
```

**Comment by zhuojiuqingyun** [comment]
@s-weissbach Thank you very much! I'll check my files and try again.
